######################################################################
# Automatically generated by qmake (3.0) Tue Apr 28 21:31:38 2015
######################################################################

TEMPLATE = app
TARGET = trening
INCLUDEPATH += .

# Input
SOURCES += program.cpp
